---

- name: Install EPEL repo
  yum:
    name: epel-release
    state: installed

- name: Install R lang RPM from Rstudio repos
  yum:
    name: "https://cdn.rstudio.com/r/centos-{{ ansible_distribution_major_version }}/pkgs/R-{{ rstudio_server_r_version }}-1-1.x86_64.rpm"
    state: installed

- name: Symlink R executable to /usr/local/bin
  file:
    src: "/opt/R/{{ rstudio_server_r_version }}/bin/R"
    dest: /usr/local/bin/R
    owner: root
    group: root
    state: link

- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present

- name: Install some extra libraries to build R packages
  yum:
    name:
      - readline-devel
      - readline-static
      - ncurses-devel
      - ncurses-static
      - libpng-devel
      - libpng-static
      - libjpeg-turbo-devel
      - libjpeg-turbo-static
      - libtiff-devel
      - libtiff-static
      - tcl-devel
      - tk-devel
      - zlib-devel
      - zlib-static
      - bzip2-devel
      - libcurl-devel
      - curl
      - libxml2-devel
      - xz-devel
      - cairo-devel
      - mpfr-devel
      - gdal-devel
    state: installed
